export const START_RECIEVE_BOOKS = "START_RECIEVE_BOOKS";
export const RECIEVE_BOOKS = "RECIEVE_BOOKS";
export const ERROR_RECIEVE_BOOKS = "ERROR_RECIEVE_BOOKS";

export const START_RECIEVE_BOOK = "START_RECIEVE_BOOK";
export const RECIEVE_BOOK = "RECIEVE_BOOK";
export const ERROR_RECIEVE_BOOK = "ERROR_RECIEVE_BOOK";

export const DELETE_BOOK = "DELETE_BOOK";
export const UNDO_DELETE_BOOK = "UNDO_DELETE_BOOK";

export const ADD_BOOK = "ADD_BOOK";